- hosts: nl_last_cloud
  become: true
  tasks:
    - name: Clean jail.d dir
      shell: |
        rm /etc/fail2ban/jail.d/defaults-debian.conf || true
        mkdir -p /var/log/caddy
        touch -a /var/log/caddy/caddy.log
    - name: Copy fail2ban jail.local configuration file
      template:
        src: templates/ssh.jail.conf
        dest: /etc/fail2ban/jail.d/ssh.local
        owner: root
        group: root
        mode: '0644'
    - name: Copy fail2ban caddy-basic-auth filter file
      template:
        src: templates/caddy-basic-auth.filter.conf
        dest: /etc/fail2ban/filter.d/caddy-basic-auth.local
        owner: root
        group: root
        mode: '0644'
    - name: Copy fail2ban jail.local configuration file
      template:
        src: templates/caddy-basic-auth.jail.conf
        dest: /etc/fail2ban/jail.d/caddy-basic-auth.local
        owner: root
        group: root
        mode: '0644'
    - name: Restart fail2ban service
      service: 
        name: fail2ban
        state: restarted
        enabled: true