- hosts: nl_last_cloud
  become: true
  vars_files:
    - vars/private.yml
  tasks:
    - name: Set mount point permissions
      shell: |
        mkdir /data
        chown 1000:1000 /data
        chmod 0775 /data  
    # Find UUID of Storage Devices
    # sudo blkid
    - name: Mount disk to data
      mount:
        path: /data
        src: UUID={{ disk_uuid }}
        fstype: btrfs
        opts: defaults,noatime
        state: present
        passno: 2